# Generated by Django 6.0.3 on 2026-03-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0004_recipient_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("once", "Однократная"),
                    ("daily", "Ежедневная"),
                    ("weekly", "Еженедельная"),
                    ("monthly", "Ежемесячная"),
                ],
                default="once",
                max_length=20,
                verbose_name="Периодичность",
            ),
        ),
    ]
